# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

      
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env

networks:
#  networks:
#    mumbai_moralis:
#      host: https://speedy-nodes-nyc.moralis.io/9974efbb9dfbbd6922950e4b/polygon/mumbai/archive



  default: development
  development:
    cmd_settings:
      mnemonic: brownie
      default_balance: 100000000000000000000
      unlock: <ACCOUNT ADDRESS HERE> # optionally add saved brownie account to Ganache
      # (requires explicit transfer of eth to accounts[-1]) 

    update_interval: 60
    verify: False

  ganache-local:
    verify: False

  kovan:

    verify: False
    update_interval: 60

  mumbai_moralis_3:
    verify: False



wallets:
  from_key: ${PRIVATE_KEY}


# enable output of development artifacts to load with react
dev_deployment_artifacts: true
